[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_PUBLIC_BASE_URL = "https://carpetcozy.com"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Disabling the sitemap plugin as we're handling it with Next.js route handler
# [[plugins]]
#   package = "@netlify/plugin-sitemap"
#   [plugins.inputs]
#     baseUrl = "https://carpetcozy.com"
#     exclude = ["/api/*"]

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = false
  minify = false

[build.processing.js]
  bundle = false
  minify = false

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# Handle static files
[[redirects]]
  from = "/_next/*"
  to = "/_next/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200

# Directly serve the static sitemap file
[[redirects]]
  from = "/sitemap.xml"
  to = "/netlify.xml"
  status = 200
  force = true

# Handle all other routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = { Method = ["GET"] }

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:;"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"
    X-Content-Type-Options = "nosniff"

[[redirects]]
  from = "/thank-you"
  to = "/thank-you"
  status = 200
  force = true

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = ".netlify/functions/*"
  to = ".netlify/functions/:splat"
  status = 200

